apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
spec:
  storageClassName: todo-app-pv-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/todoapp"
