apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-container
              image: PG_BACKUP_IMAGE
              imagePullPolicy: IfNotPresent
              env:
                - name: POSTGRES_URL
                  valueFrom:
                    secretKeyRef:
                      name: project-secret
                      key: DB_URL
                - name: GCS_BUCKET
                  value: "todo-app-storage-8123"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/var/secrets/google/pg-backup-key.json"
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                  readOnly: true
          volumes:
            - name: google-cloud-key
              secret:
                secretName: google-service-account-key
          restartPolicy: OnFailure
