apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: todo-backend-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz
        port: 8085
  targetRef:
    group: ""
    kind: Service
    name: todo-backend-svc
