apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
spec:
  template:
    spec:
      containers:
        - name: todo-broadcaster-app
          env:
            - name: APP_ENV
              value: "production"
